version: '3'

services: 
  chatbot-nlu: 
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/nlu:latest
    networks:
      - chatbot
      - nlu
  duckling:
    image: rasa/duckling:latest
    networks:
      - nlu
networks:
  chatbot:
    external: true
  nlu:
